// Post-build step. Reads src/routes.js and emits, into dist/:
//   - one static HTML file per route, each with its own title, description
//     and self-referencing canonical
//   - _redirects (legacy 301s, per-route rewrites, a real-404 catch-all)
//   - sitemap.xml, with lastmod set to the build date
//
// Why this exists: the app is client-rendered, so Netlify used to serve
// byte-identical HTML for every URL - including a canonical pointing at
// the homepage. Googlebot canonicalises from the raw HTML on its first
// pass, long before it renders the JS that PageMeta runs in, so all five
// routes were consolidated into "/" and only the homepage was indexed.
// Patching the head client-side is too late to matter.
//
// Every replacement below is asserted to match exactly once. If the
// template in index.html changes shape, this build fails loudly rather
// than silently shipping homepage canonicals again.

import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { SITE, routes, legacyRedirects } from "../src/routes.js";

const DIST = "dist";

const escapeText = (s) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const escapeAttr = (s) => escapeText(s).replace(/"/g, "&quot;");

function replaceOne(html, pattern, replacement, label) {
  const matches = html.match(pattern);
  if (!matches || matches.length !== 1) {
    throw new Error(
      `generate-pages: expected exactly 1 match for ${label}, found ${
        matches ? matches.length : 0
      }. The <head> template in index.html has changed - update this script.`,
    );
  }
  // replacement is a plain string, so escape $ to stop it being read as a
  // capture-group reference
  return html.replace(pattern, replacement.replace(/\$/g, "$$$$"));
}

const urlFor = (path) => SITE + path;

// --- one HTML file per route -------------------------------------------

const template = await readFile(join(DIST, "index.html"), "utf8");

for (const route of routes) {
  const url = urlFor(route.path);
  const title = escapeText(route.title);
  const titleAttr = escapeAttr(route.title);
  const descAttr = escapeAttr(route.description);

  let html = template;

  const swaps = [
    [/<title>[\s\S]*?<\/title>/g, `<title>${title}</title>`, "<title>"],
    [
      /<meta\s+name="description"[\s\S]*?\/>/g,
      `<meta name="description" content="${descAttr}" />`,
      'meta[name="description"]',
    ],
    [
      /<link\s+rel="canonical"[^>]*\/>/g,
      `<link rel="canonical" href="${url}" />`,
      'link[rel="canonical"]',
    ],
    [/<meta\s+property="og:url"[^>]*\/>/g, `<meta property="og:url" content="${url}" />`, "og:url"],
    [
      /<meta\s+property="og:title"[^>]*\/>/g,
      `<meta property="og:title" content="${titleAttr}" />`,
      "og:title",
    ],
    [
      /<meta\s+property="og:description"[^>]*\/>/g,
      `<meta property="og:description" content="${descAttr}" />`,
      "og:description",
    ],
    [
      /<meta\s+name="twitter:title"[^>]*\/>/g,
      `<meta name="twitter:title" content="${titleAttr}" />`,
      "twitter:title",
    ],
    [
      /<meta\s+name="twitter:description"[^>]*\/>/g,
      `<meta name="twitter:description" content="${descAttr}" />`,
      "twitter:description",
    ],
  ];

  for (const [pattern, replacement, label] of swaps) {
    html = replaceOne(html, pattern, replacement, label);
  }

  await writeFile(join(DIST, route.file), html, "utf8");
  console.log(`generate-pages: ${route.file.padEnd(14)} -> ${url}`);
}

// --- _redirects ---------------------------------------------------------
//
// Netlify matches top-down and, without the force flag, an existing file
// shadows a rule. The explicit "/" rule is defensive: the catch-all below
// returns a real 404 status, and the homepage must never fall into it.

const pad = (s, n) => s.padEnd(n);

const redirects = [
  "# Generated by scripts/generate-pages.js - do not edit by hand.",
  "",
  "# The capitalised URLs were live and are in Google's index. 301 rather",
  "# than drop them, so any accumulated signals follow to the new paths.",
  ...legacyRedirects.map(({ from, to }) => `${pad(from, 12)}${pad(to, 16)}301!`),
  "",
  "# Real routes: serve that route's prerendered HTML, so the canonical in",
  "# the raw response matches the URL that was requested.",
  `${pad("/", 12)}${pad("/index.html", 16)}200`,
  ...routes
    .filter((r) => r.path !== "/")
    .map((r) => `${pad(r.path, 12)}${pad("/" + r.file, 16)}200`),
  "",
  "# Everything else boots the SPA, which renders NotFound - but with a",
  "# genuine 404 status rather than a soft 404 that Google would try to",
  "# index.",
  `${pad("/*", 12)}${pad("/index.html", 16)}404`,
  "",
].join("\n");

await writeFile(join(DIST, "_redirects"), redirects, "utf8");
console.log("generate-pages: _redirects");

// --- sitemap.xml --------------------------------------------------------

const lastmod = new Date().toISOString().slice(0, 10);

const sitemap = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ...routes.flatMap((r) => [
    "  <url>",
    `    <loc>${urlFor(r.path)}</loc>`,
    `    <lastmod>${lastmod}</lastmod>`,
    "  </url>",
  ]),
  "</urlset>",
  "",
].join("\n");

await writeFile(join(DIST, "sitemap.xml"), sitemap, "utf8");
console.log(`generate-pages: sitemap.xml   (lastmod ${lastmod})`);
